---
- hosts: test-servers
  sudo : yes
  vars : 
    username: t.otsuka
# 実行時にプロンプトから入力
#  vars_prompt: 
#    username: "Enter username"

  tasks:
    - name: add new user
      user: name={{username}}

    - name: be sure httpd is installed 
      yum: name=httpd state=installed

    - name: be sure httpd is running and enabled
      service: name=httpd state=running enabled=yes 

    - name: change owner
      file: dest=/var/www/html owner={{username}} recurse=yes

    - name: copy index.html
      copy: src=./index.html dest=/var/www/html/index.html owner={{username}}
    - name: copy index.php
      copy: src=./index.php dest=/var/www/html/index.php owner={{username}}

    - name: install php packages
      yum: name={{item}} state=latest
      with_items: 
        - php
        - php-devel
        - php-mbstring
        - php-mysql
      notify:
        - restart apache
        
  handlers:
    - name: restart apache
      service: name=httpd state=restarted


